export const SITE_CONFIG = {
  name: "QuickWay Ride",
  tagline: "Premium Taxi Booking & Travel Management Platform",
  companyName: "QuickWay Ride",
  region: "Uttarakhand & Nearby Regions",
  contact: {
    phoneHotline: "+91 8679506655",
    phoneDisplay: "+91 8679506655",
    whatsappNumber: "+91 8679506655",
    supportEmail: "info@quickwayride.com",
    emergencyPhone: "+91 8679506655",
    officeAddress: "1st Floor, Opposite to Shiv Sani Mandir, Near Sai Lok Gate, GMS Road, Dehradun",
    cityAddress: "Roorkee & Dehradun, Uttarakhand, India",
    googleMapUrl: "https://maps.app.goo.gl/mESPwJUT69WaT6Pa6?g_st=awb",
    businessHours: "24 Hours / 7 Days a Week",
  },
  social: {
    facebook: "https://facebook.com/quickwayride",
    instagram: "https://instagram.com/quickwayride",
    twitter: "https://twitter.com/quickwayride",
    linkedin: "https://linkedin.com/company/quickwayride",
    whatsapp: "https://wa.me/918679506655",
  },
  navLinks: [
    { label: "Home", href: "/" },
    { label: "About Us", href: "/about" },
    { label: "Services", href: "/services" },
    { label: "Fleet", href: "/fleet" },
    { label: "Pricing", href: "/pricing" },
    { label: "Tour Packages", href: "/packages" },
    { label: "Gallery", href: "/gallery" },
    { label: "Contact", href: "/contact" },
  ],
  legalLinks: [
    { label: "Privacy Policy", href: "/privacy" },
    { label: "Terms & Conditions", href: "/terms" },
    { label: "Cancellation Policy", href: "/cancellation-policy" },
    { label: "Refund Policy", href: "/refund-policy" },
  ],
  secondaryLinks: [
    { label: "Service Areas", href: "/service-areas" },
    { label: "Corporate Cabs", href: "/corporate" },
    { label: "Book Cabs", href: "/book" },
    { label: "Request Quote", href: "/quote" },
  ],
  seoDefaults: {
    title: "QuickWay Ride - Premium Taxi & Outstation Cabs in Uttarakhand",
    description: "Book reliable, safe, and comfortable taxis in Roorkee, Haridwar, Rishikesh, Dehradun, Saharanpur. Instant fare quotes, outstation drops & tour packages.",
    url: "https://quickwayride.com",
    ogImage: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?q=80&w=1200",
  },
};
