import { Testimonial } from "./testimonials.types";

export const TESTIMONIALS_DATA: Testimonial[] = [
  {
    id: "test-1",
    name: "Rahul Sharma",
    designation: "Software Engineer",
    city: "Roorkee",
    rating: 5,
    review: "Outstanding service. The driver arrived 15 minutes before time, the Innova Crysta was spotless, and the entire journey from Roorkee to Delhi Airport was smooth, safe, and comfortable.",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    featured: true,
    is_active: true,
    created_at: "2026-02-10T10:00:00Z",
  },
  {
    id: "test-2",
    name: "Priya Verma",
    designation: "Architect",
    city: "Dehradun",
    rating: 5,
    review: "QuickWay Ride made our Char Dham hill family trip memorable! Zero hidden costs, transparent billing, and a extremely polite chauffeur who guided us through the mountain routes with complete safety.",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    featured: true,
    is_active: true,
    created_at: "2026-02-12T14:30:00Z",
  },
  {
    id: "test-3",
    name: "Vikram Malhotra",
    designation: "Corporate Director",
    city: "Delhi NCR",
    rating: 5,
    review: "We regularly book QuickWay Ride for executive corporate delegations travelling between IGI Airport Delhi, Haridwar, and Rishikesh. Punctual, luxury fleet, and hassle-free GST invoicing.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    featured: true,
    is_active: true,
    created_at: "2026-02-14T09:15:00Z",
  },
  {
    id: "test-4",
    name: "Dr. Ananya Joshi",
    designation: "Medical Specialist",
    city: "Rishikesh",
    rating: 5,
    review: "Night emergency travel from Rishikesh to Jolly Grant Airport was handled flawlessly. Clean sanitized vehicle, professional driver, and constant live GPS tracking gave my family complete peace of mind.",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    featured: true,
    is_active: true,
    created_at: "2026-02-18T16:20:00Z",
  },
  {
    id: "test-5",
    name: "Siddharth Rawat",
    designation: "Research Scholar",
    city: "IIT Roorkee",
    rating: 5,
    review: "Booked a sedan cab for my parents visiting Roorkee & Mussoorie. Highly affordable fixed rates with no surge pricing. The driver was helpful and courteous throughout the 3-day trip.",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    featured: true,
    is_active: true,
    created_at: "2026-02-20T11:45:00Z",
  },
  {
    id: "test-6",
    name: "Meenakshi Sundaram",
    designation: "Pilgrimage Group Organizer",
    city: "Chennai",
    rating: 5,
    review: "Our group of 14 booked a Maharaja Tempo Traveller from QuickWay Ride for Haridwar to Badrinath. The vehicle was equipped with recliner seats, AC, and our driver was experienced in hilly terrains.",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    featured: true,
    is_active: true,
    created_at: "2026-02-22T08:00:00Z",
  },
];
